name: gitee sync

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    #- cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository list exclude private and fork
      id: repo
      uses: yi-Xu-0100/repo-list-generator@v1.0.1

    - name: mirror the github repos to gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/vsfteam
        dst: gitee/vsfteam
        account_type: org
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        debug: true
        static_list: ${{ steps.repo.outputs.repoList }}, ${{ steps.repo.outputs.repoList_FORK }}
        black_list: vsfteam.github.io
        timeout: '20m'
